Correct the package name
Now the murano-pkg-check gives the error:
Exception: Versioning for this project requires either an sdist tarball,
or access to an upstream git repository. Are you sure that git is installed?
This patch correct the package name when get the package version.

Change-Id: I33500b3527e21a513f9130f55f0b54ba0e047d5f
Closes-Bug: #1653060